name: pl
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkit=11.0
  - tensorboard
  - future
  - tornado
  - decorator
  - filelock
  - joblib
  - regex
  - pyparsing
  - packaging
  - pip:
    - sentencepiece
    - python-telegram-bot
    - transformers
    - torch_optimizer
