name: pl
channels:
  - pytorch
  - defaults
  - huggingface
dependencies:
  - pip
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkit=11.0
  - tensorboard
  - nltk
  - transformers
  - APScheduler
  - decorator
  - tornado
  - pip:
    - sentencepiece
    - python-telegram-bot
    - graphviz
    - mecab-python3
