name: pl
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkit=11.0
  - tensorboard
  - tornado
  - nltk
  - APScheduler
  - decorator
  - filelock
  - packaging
  - pip:
    - sentencepiece
    - python-telegram-bot
    - transformers
    - graphviz
